### ISSUE TITLE
[Bug]: soundImpactStuff should now be soundImpactBullet

### ISSUE THREAD

**Issue by HugKitten** [SirLalaPyon/MedievalOverhaul#53]
XML error: <soundImpactStuff>BulletImpact_Wood</soundImpactStuff> doesn't correspond to any field in type

I think you need to change soundImpactStuff to soundImpactBullet to fix this error.

**Comment by SirLalaPyon** [comment]
BulletImpact_Wood exists in core

**Comment by SirLalaPyon** [comment]
fixed
