### ISSUE TITLE
[Bug]: System.InvalidCastException (HugsLib attached)

### ISSUE THREAD

**Issue by feeddanoob** [SirLalaPyon/MedievalOverhaul#68]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version:  1.5.4104
Medieval Overhaul version: fb4a4ee03a2c343fa098d7dcc891127cad454a4c
Medieval Overhaul source (Steam, GitHub, etc.): GitHub
Your operating system: Windows 11
Your mod list: 
https://rentry.co/dc2buwsv

**Description**
Provide a concise description of the issue or concern. What happened?

Start game errors from the recent Medieval Overhaul changes to books.

**Expected behavior**
What did you expect to happen?

No errors on start.

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?

Clone from Git to Rimworld mods directory, install prereqs, check log for invalid cast type.

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here.

[HugsLib](https://gist.github.com/HugsLibRecordKeeper/d560f11f8288a8981e8060d8d584a527#file-output_log-txt-L1570)

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Medieval Overhaul.
- [x] Confirmed I am not running any mods with known incompatibilities with Medieval Overhaul.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SirLalaPyon** [comment]
Github is currently unstable, books are still WIP. Try downloading earlier versions.

**Comment by feeddanoob** [comment]
Will do, I went down to 4751ada7bb8993c4d2376cfe631fe59e6c97367e since I think I didn't have an issue from there. Thank you and the team for all the updates you do for the mod.
